Feature 3 building houses and hotels
CSC207-2022F-UofT/course-project-monopolymen pull request #42
Opened 2022-11-18 23:16 UTC by SDunk1011

2022-11-19 23:09 UTC, JLenander commented on src/main/java/TurnUseCases/BuildUseCase/BuildBuildingInputBoundary.java
> +public interface BuildBuildingInputBoundary {
Do we want BuildBuilding use case to also have methods for selling houses and hotels?

2022-11-19 23:13 UTC, JLenander commented on src/main/java/TurnUseCases/BuildUseCase/BuildBuildings.java
> +        if(!property.getClass().getName().equals("GameEntities.Tiles.ColorPropertyTile")){
If you're checking the class of the object, you can use `property instanceof ColorPropertyTile`

2022-11-19 23:17 UTC, JLenander requested changes
Lines 34-62 in `BuildBuildings.java` isn't necessary and should use the entity method. The ColorPropertyTile class has a method for checking if they own the whole set (`colorPropertyTile.checkSetOwned`).
Lines 86-104 in `BuildBuildings.java` should use the method `colorPropertyTile.getBuildingCost` (same for the `buildHotel` method.
See e40f2aae15067f77e9d9bc59dfa160ec495e37f5 for the updated ColorPropertyTile code

2022-11-21 16:32 UTC, JLenander commented
Same as #34 , the Presenter being in all of the method signatures indicates that you can have the presenter as an instance variable (passing it into the constructor) instead of passing it into every method.

2022-11-28 09:18 UTC, Youssefb1234 commented on src/main/java/TurnUseCases/BuildUseCase/BuildBuildings.java
> +            //need to add a method addHotel in ColorPropertyTile class to add the number of hotel.
I added the add house and add hotel methods in color property tile so you should be able to implement the remaining build methods.

2022-12-01 21:33 UTC, alirezazim03 approved these changes

2022-12-01 22:32 UTC, iamyanbo approved these changes

2022-12-01 22:33 UTC, JLenander approved these changes

2022-12-01 22:36 UTC, TahirLeonenko approved these changes

2022-12-01 22:36 UTC, merged